# Generated by Django 5.1.2 on 2024-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_color_alter_item_name_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
